ALTER TABLE "User" ADD COLUMN "activeSessionId" TEXT;
ALTER TABLE "User" ADD COLUMN "sessionTimeoutMinutes" INTEGER NOT NULL DEFAULT 30;
ALTER TABLE "Task" ADD COLUMN "revisedDate" TIMESTAMP(3);
ALTER TABLE "Task" ADD COLUMN "progress" INTEGER NOT NULL DEFAULT 0;
